### ISSUE TITLE
ArgumentException: endpoint is not set

### ISSUE THREAD

**Issue by PratikInkey** [microsoft/Partner-Center-Storefront#26]
While trying to run the project from visual studio, I am getting following exception:

**File Name:** Global.asax.cs
**Line Number:** 39
**Line Code:** Task.Run(() => ApplicationDomain.BootstrapAsync()).Wait();

**Exception Details:**
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Store.PartnerCenter.Storefront.MvcApplication.Application_Start() in C:\Users\User1\Desktop\Partner Center Storefront\src\Storefront\Global.asax.cs:line 39

**Inner Exception:**
ArgumentException: endpoint is not set

Am I missing the any initial steps we need to perform before we can successfully build/run the solution?

**Comment by isaiahwilliams** [comment]
This exception is being encountered because one of the required configurations values is not set. The line of code throwing this exception can be found [here](https://github.com/microsoft/Partner-Center-Storefront/blob/master/src/Storefront/BusinessLogic/KeyVaultService.cs#L37). To resolve you will need to deploy and configure an instance of Azure Key Vault. 

I would recommend using the ARM template to deploy the solution to Azure once. That you can have an easy way to compare the required application configurations to what you have locally in Visual Studio.

**Comment by mfansari82** [comment]
> This exception is being encountered because one of the required configurations values is not set. The line of code throwing this exception can be found [here](https://github.com/microsoft/Partner-Center-Storefront/blob/master/src/Storefront/BusinessLogic/KeyVaultService.cs#L37). To resolve you will need to deploy and configure an instance of Azure Key Vault.
> 
> I would recommend using the ARM template to deploy the solution to Azure once. That you can have an easy way to compare the required application configurations to what you have locally in Visual Studio.

without deploy on azure, is their way to run in local system
i am not understand this
""partnercenterApiEndpoint": {
      "type": "string",
      "defaultValue": "https://api.partnercenter.microsoft.com"
    }" 
should i change this default value or any other thing i do for this.
I try to change this still i get same error. so can you please guide me where i put this end point value
